package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mvvm.lux.burqa.model.entity.SearchHistoryInfo;

import greendao.SearchHistoryInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistoryInfoDaoConfig;

    private final SearchHistoryInfoDao searchHistoryInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistoryInfoDaoConfig = daoConfigMap.get(SearchHistoryInfoDao.class).clone();
        searchHistoryInfoDaoConfig.initIdentityScope(type);

        searchHistoryInfoDao = new SearchHistoryInfoDao(searchHistoryInfoDaoConfig, this);

        registerDao(SearchHistoryInfo.class, searchHistoryInfoDao);
    }
    
    public void clear() {
        searchHistoryInfoDaoConfig.clearIdentityScope();
    }

    public SearchHistoryInfoDao getSearchHistoryInfoDao() {
        return searchHistoryInfoDao;
    }

}
